/*
 * This file is generated by jOOQ.
*/
package models.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Etudiants;
import models.tables.records.EtudiantsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EtudiantsDao extends DAOImpl<EtudiantsRecord, models.tables.pojos.Etudiants, Integer> {

    /**
     * Create a new EtudiantsDao without any configuration
     */
    public EtudiantsDao() {
        super(Etudiants.ETUDIANTS, models.tables.pojos.Etudiants.class);
    }

    /**
     * Create a new EtudiantsDao with an attached configuration
     */
    public EtudiantsDao(Configuration configuration) {
        super(Etudiants.ETUDIANTS, models.tables.pojos.Etudiants.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.tables.pojos.Etudiants object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<models.tables.pojos.Etudiants> fetchById(Integer... values) {
        return fetch(Etudiants.ETUDIANTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public models.tables.pojos.Etudiants fetchOneById(Integer value) {
        return fetchOne(Etudiants.ETUDIANTS.ID, value);
    }

    /**
     * Fetch records that have <code>nom IN (values)</code>
     */
    public List<models.tables.pojos.Etudiants> fetchByNom(String... values) {
        return fetch(Etudiants.ETUDIANTS.NOM, values);
    }

    /**
     * Fetch records that have <code>promon IN (values)</code>
     */
    public List<models.tables.pojos.Etudiants> fetchByPromon(String... values) {
        return fetch(Etudiants.ETUDIANTS.PROMON, values);
    }

    /**
     * Fetch records that have <code>telephone IN (values)</code>
     */
    public List<models.tables.pojos.Etudiants> fetchByTelephone(String... values) {
        return fetch(Etudiants.ETUDIANTS.TELEPHONE, values);
    }

    /**
     * Fetch records that have <code>date_naissance IN (values)</code>
     */
    public List<models.tables.pojos.Etudiants> fetchByDateNaissance(Date... values) {
        return fetch(Etudiants.ETUDIANTS.DATE_NAISSANCE, values);
    }

    /**
     * Fetch records that have <code>id_classe IN (values)</code>
     */
    public List<models.tables.pojos.Etudiants> fetchByIdClasse(Integer... values) {
        return fetch(Etudiants.ETUDIANTS.ID_CLASSE, values);
    }
}
