/*
 * This file is generated by jOOQ.
*/
package models.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import models.tables.Etudiants;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EtudiantsRecord extends UpdatableRecordImpl<EtudiantsRecord> implements Record6<Integer, String, String, String, Date, Integer> {

    private static final long serialVersionUID = 1194670780;

    /**
     * Setter for <code>public.Etudiants.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Etudiants.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Etudiants.nom</code>.
     */
    public void setNom(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Etudiants.nom</code>.
     */
    public String getNom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.Etudiants.promon</code>.
     */
    public void setPromon(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.Etudiants.promon</code>.
     */
    public String getPromon() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.Etudiants.telephone</code>.
     */
    public void setTelephone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.Etudiants.telephone</code>.
     */
    public String getTelephone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.Etudiants.date_naissance</code>.
     */
    public void setDateNaissance(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.Etudiants.date_naissance</code>.
     */
    public Date getDateNaissance() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>public.Etudiants.id_classe</code>.
     */
    public void setIdClasse(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.Etudiants.id_classe</code>.
     */
    public Integer getIdClasse() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Date, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Date, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Etudiants.ETUDIANTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Etudiants.ETUDIANTS.NOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Etudiants.ETUDIANTS.PROMON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Etudiants.ETUDIANTS.TELEPHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Etudiants.ETUDIANTS.DATE_NAISSANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Etudiants.ETUDIANTS.ID_CLASSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPromon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getIdClasse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPromon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIdClasse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudiantsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudiantsRecord value2(String value) {
        setNom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudiantsRecord value3(String value) {
        setPromon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudiantsRecord value4(String value) {
        setTelephone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudiantsRecord value5(Date value) {
        setDateNaissance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudiantsRecord value6(Integer value) {
        setIdClasse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EtudiantsRecord values(Integer value1, String value2, String value3, String value4, Date value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EtudiantsRecord
     */
    public EtudiantsRecord() {
        super(Etudiants.ETUDIANTS);
    }

    /**
     * Create a detached, initialised EtudiantsRecord
     */
    public EtudiantsRecord(Integer id, String nom, String promon, String telephone, Date dateNaissance, Integer idClasse) {
        super(Etudiants.ETUDIANTS);

        set(0, id);
        set(1, nom);
        set(2, promon);
        set(3, telephone);
        set(4, dateNaissance);
        set(5, idClasse);
    }
}
