/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classe implements Serializable {

    private static final long serialVersionUID = -854412574;

    private Integer id;
    private String  libelle;

    public Classe() {}

    public Classe(Classe value) {
        this.id = value.id;
        this.libelle = value.libelle;
    }

    public Classe(
        Integer id,
        String  libelle
    ) {
        this.id = id;
        this.libelle = libelle;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Classe (");

        sb.append(id);
        sb.append(", ").append(libelle);

        sb.append(")");
        return sb.toString();
    }
}
