/*
 * This file is generated by jOOQ.
*/
package models.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Etudiants implements Serializable {

    private static final long serialVersionUID = -907635959;

    private Integer id;
    private String  nom;
    private String  promon;
    private String  telephone;
    private Date    dateNaissance;
    private Integer idClasse;

    public Etudiants() {}

    public Etudiants(Etudiants value) {
        this.id = value.id;
        this.nom = value.nom;
        this.promon = value.promon;
        this.telephone = value.telephone;
        this.dateNaissance = value.dateNaissance;
        this.idClasse = value.idClasse;
    }

    public Etudiants(
        Integer id,
        String  nom,
        String  promon,
        String  telephone,
        Date    dateNaissance,
        Integer idClasse
    ) {
        this.id = id;
        this.nom = nom;
        this.promon = promon;
        this.telephone = telephone;
        this.dateNaissance = dateNaissance;
        this.idClasse = idClasse;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPromon() {
        return this.promon;
    }

    public void setPromon(String promon) {
        this.promon = promon;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public Date getDateNaissance() {
        return this.dateNaissance;
    }

    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    public Integer getIdClasse() {
        return this.idClasse;
    }

    public void setIdClasse(Integer idClasse) {
        this.idClasse = idClasse;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Etudiants (");

        sb.append(id);
        sb.append(", ").append(nom);
        sb.append(", ").append(promon);
        sb.append(", ").append(telephone);
        sb.append(", ").append(dateNaissance);
        sb.append(", ").append(idClasse);

        sb.append(")");
        return sb.toString();
    }
}
