/*
 * This file is generated by jOOQ.
*/
package models;


import javax.annotation.Generated;

import models.tables.Classe;
import models.tables.Etudiants;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CLASSE_PK = Indexes0.CLASSE_PK;
    public static final Index ETUDIANT_PK = Indexes0.ETUDIANT_PK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index CLASSE_PK = createIndex("classe_pk", Classe.CLASSE, new OrderField[] { Classe.CLASSE.ID }, true);
        public static Index ETUDIANT_PK = createIndex("etudiant_pk", Etudiants.ETUDIANTS, new OrderField[] { Etudiants.ETUDIANTS.ID }, true);
    }
}
