/*
 * This file is generated by jOOQ.
*/
package models;


import javax.annotation.Generated;

import models.tables.Classe;
import models.tables.Etudiants;
import models.tables.records.ClasseRecord;
import models.tables.records.EtudiantsRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ClasseRecord, Integer> IDENTITY_CLASSE = Identities0.IDENTITY_CLASSE;
    public static final Identity<EtudiantsRecord, Integer> IDENTITY_ETUDIANTS = Identities0.IDENTITY_ETUDIANTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClasseRecord> CLASSE_PK = UniqueKeys0.CLASSE_PK;
    public static final UniqueKey<EtudiantsRecord> ETUDIANT_PK = UniqueKeys0.ETUDIANT_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EtudiantsRecord, ClasseRecord> ETUDIANTS__ETUDIANT_CLASSE = ForeignKeys0.ETUDIANTS__ETUDIANT_CLASSE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ClasseRecord, Integer> IDENTITY_CLASSE = createIdentity(Classe.CLASSE, Classe.CLASSE.ID);
        public static Identity<EtudiantsRecord, Integer> IDENTITY_ETUDIANTS = createIdentity(Etudiants.ETUDIANTS, Etudiants.ETUDIANTS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ClasseRecord> CLASSE_PK = createUniqueKey(Classe.CLASSE, "classe_pk", Classe.CLASSE.ID);
        public static final UniqueKey<EtudiantsRecord> ETUDIANT_PK = createUniqueKey(Etudiants.ETUDIANTS, "etudiant_pk", Etudiants.ETUDIANTS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<EtudiantsRecord, ClasseRecord> ETUDIANTS__ETUDIANT_CLASSE = createForeignKey(models.Keys.CLASSE_PK, Etudiants.ETUDIANTS, "Etudiants__etudiant_classe", Etudiants.ETUDIANTS.ID_CLASSE);
    }
}
