/*
 * This file is generated by jOOQ.
*/
package models;


import javax.annotation.Generated;

import models.tables.Classe;
import models.tables.Etudiants;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.Classe</code>.
     */
    public static final Classe CLASSE = models.tables.Classe.CLASSE;

    /**
     * The table <code>public.Etudiants</code>.
     */
    public static final Etudiants ETUDIANTS = models.tables.Etudiants.ETUDIANTS;
}
